### ISSUE TITLE
Run tests in Windows environment

### ISSUE THREAD

**Issue by agarzola** [ChromaticHQ/calliope#16]
## Description

We have Windows users in our midst! We should ensure that Windows systems can run all Calliope commands.

## Proposed Solution

Run our unit tests in Windows as we do for POSIX systems (via ubuntu). It would be awesome if we could do this via a `platform` dimension on our testing job matrix, but that may not be possible. Some research is in order.

## Alternatives Considered

n/a

## Additional Context

n/a

**Comment by Boegie** [comment]
Looks like GitHub has Windows Server 2019 and 2022 test-runners:

https://github.blog/changelog/2021-11-16-github-actions-windows-server-2022-with-visual-studio-2022-is-now-generally-available-on-github-hosted-runners/
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by agarzola** [comment]
> Not a clue TBH, but for things like a general "This doesn't work on Windows, but will work if we do it slightly differently for Windows base machines using a check like `process.platform === 'win32'`" (as seen in #15), I don't think we have to worry about internal differences between Windows versions.
> Having a basic "This will run on Windows (at least most/some/one of them" will take away a lot of "pain" already.

That makes a lot of sense. I’ll just pick `windows-latest` and if that somehow doesn’t catch certain cases that do affect real users on Windows 10/11, then we can pivot from there.

Thanks again for your guidance here!
