### ISSUE TITLE
Create test SCSS files

### ISSUE THREAD

**Issue by agarzola** [ChromaticHQ/calliope#22]
## Description

With the goal to make this package both reliable _and_ easy to work on and extend, we should be testing every task that Calliope ships with. To that end, we need test SCSS that our tests can build for the purposes of testing the `styles` task.

## Proposed Solution

Create a `tests/styles/samples/` directory with a set of stylesheets in it that are largely representative of the kind of SCSS we write for our projects. It should include features such as:
- Importing partials via globs.
- tk

Additionally, we will need a set of generated CSS against which our tests can compare the results of running the `styles` task.

## Alternatives Considered

n/a

**Comment by michelegrace** [comment]
I started getting the barebones of this going, but I've never really written tests before, so I have a lot of questions (sorry if any of these are silly!). I have a few starter "tests" aka the `describe()` and some `it`s which will test:
- Styles are linting properly (also have to check to see if the configuration for linting is activated or not?)
- Importing using globs.
- Autoprefixer works.
- Filename changes.
- Stylesheet is getting minfied.

Basically all the steps in the styles task (except `sass(config.plugins.sass).on('error', sass.logError)`, does that also need testing?), but don't have anything filled in yet and now I'm trying to set up a sample styles directory and have some questions. My initial thought is that within `tests/styles/samples/` there should be a `scss` with the raw sass and a `css` with the compiled CSS, is that correct?

Ideally, what is happening is that mocha is attempting to compile the `scss` according to `style` tasks and comparing it to the compiled CSS in `css`? 

Also for testing `gulp-sass-glob` should that include npm libraries we often use such as `breakpoint-sass`? Would then including a `package.json` for it in `tests/styles/samples` be useful or if that overkill?
